apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgCBt2J1RpW8rTJglqjYkUj5IYI+TqI44kWODIOM3qZq8fr026jlSNLwp3Ld3d5hZc3tIZexiv3dgcZ59dyPPKQWZBiKQjIU9CqwO1I1dCF2uCxX0GW1Zkk7HVmB2fgXQwx8LF8/NVDi8VuAE3WF9UG6IZ/sQ0WZMWFeFHq/eo4w1WMjIUzEz+z105HebIoeT73nUGfK6NCwZE8nwoVJBPSJXQyOEJ4hoMHK1Pc7qt1kZgCcwscR6TuqBujzBapWwfiftNht8tNqzJxruh86dygdd4/aQ/ZA3eGvhxyuhCQeHW9QJngvpFVcxkamAZTH2AfScVotqR+PPdyDGcuZ6TY6Hprdg7pWrZHM+Ky//pZpMZ46fMDgPpVQyOUf89BcTvrGeZAXwu1JR6hlbcMByMlrDwnfwn/LgvzXiujNqfJtnlU/rWhcFkbvL7ASclIKdzXRZ0Y6z9QcpUUVNgvBMBgOe2An0VIVmXjmnoRr59ocaphXqDXtoXNS155VJCSvU/VP5lJCbeNk99dZWB2I4jnKzSnNwyJAj+7J0OQbGJ5QDaEhzi878cWdpqpkprPDg+9jEw5EcoTo3suj2fT2Kbu4EfWbipY0CNjmdoTFrIWK5F2K23k35RxXlLiwbSSs69l9nK+nU5mO6ryszuOfJKQB9vhARS/OzxKOTfcP7F93vJcWUrWtUGh3+QFUoQ5894BQLs4CXwNVyfI/OMpwnWb2hhrg88/GdEr46XU/ovBNj7+glgNuRAm235iK4AlViPBwWlI2gn5vnzrtjfpq1BhyFPP5DH4/R0+sUXtPfrVtKvwpwNjG3iDp8IMEf8IWAHnjNTmn/pM0hojS03Kjjcn/j3KrLxnLwojZn+6ZBq7DIfrE7smkJPcPYJ4ijjGPMdBDOEaaJI8jS/TWvi2qOrEPR+ZlDTRfGWB3fH8cHotgSJafls6xdjsF72VxmRTTjXU=
    IBM_ENTITLED_REGISTRY_USER: AgAY1aNxzLT5kSgK5zLSV3beGdMoWvrrtTuvf8WMvsNQI9XVsOYvacZWhltIZj7J+2zXlXY1eWMTWiGEQ4N0zw4F4qehWoQCI48aL5ejj+JZuJlS6lrK6wfsapTW46X/6qky+rAAYwQmYMMhnuYI5UalJqbckE1XDCrGxnR6ryXUqDlMV5UPvvtZZqBJBdk2RPUgTNCx/TT2CiPZcq78kva42MtrbLR7Xk11J74EhBaJW/fwPe+Yhmr6SM4LRz9JmGNrLOFOKbX4V1N5R6xbt/mfgB8YAe8UirTp6N+B7ooZNezHgjlwlJWbt837GRnmcb/zpr2cbRpHs5VGMZIdZTPsPlldHJNiO4T2HtKJbZrp1QG3pIS9vwx33KCFO1B4Kr/PXPBSVAewAVJ4ufT+AokB90198S5gZtKIiZgg8PuABUjspSm6w4iXT3Tak0TtdLVfTmv9b3jmtyar3u29R+C6W2SmF2uDtwOLgm9pPoj+ZnqBsfM4bUoolQ2UoB4TQQ55k4NzuoJaTZ4cE/fnZBchfLEKCRmru4/vifAJ6/anJ5/lViiBuNc/wY0B4tiyW56YCkh/8N3fneg5CQQD5p5EdqctEPLAox8c9qnvJd9Z3P93CaFST4bj/WseD3vMWNWwYWx6nV2KV+ydZS6s4EjK1nhX5LtEPWh8wf+tk60XMp84A+A2VY9NDugXmxR0NhTcxg==
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

