apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgCMctwrVHXkh6R84yyJrIYeLfbdNKCesqUjfKwv7dHn7qpQS/KkAuUyLDv9HCPiH2HBnpoUyNqUFwZp715v9blfVDTqNDqE8NfE+mzuBOzliRRdY8TMIRkTMsKRCGN5hcLPbuBKkrlu9l1vhfBOhM8a96zzlWP/MwDRFzgpsSJNR7IN9qeyQIm/U7mC1MvNdpAzCNRByN7XiYTDghPf4iPVv8rnDlcSegQW5RNXPX6xX+4cmhN3/OjrbsCtrtYcEia6Jp9h+b034Ce15Nu6DFffDjXM2a934NyU2tcp7RASQ6gNRWQPxaZ9eDyk67CTqH5acJDXNllHSjw/5alBwMQSiUxIudCRDUvjXXpUWMZUklLOiI0lgnUhevxO/cjaM/11t7kP8d7JGSfZfr/gdlvH7bl9KnASEvHDipcRSZv0knvVBD4Eeg/bdeKg+qwP+xDkNBpf+w6PZjoFrCzcE2LcRGezzfWvkoM9R6rxgw1CR00Lv5zl3tv8dxx2Df94saY+U0IjfywJfOXxyZhHpKXis+fcS7cS4L7399/TNUyMH29R2ZzYqEEaFm4ldGHFHK+lta9zmJ8do1L/dWEmb9j2fD+2qywUMvmeuUC+3WN1JkL3Lj2SuLV+6MCYfPVqrytMZPKnNyE7gIpx1J6mQVq669dTCm+4dtHujMmW/BAnHy7gqOlvJOq5xA+ofTtSHu1mKtQjydKROggfXGq6k3QWurmKoCoUUVCvYpR+1EFcextg0LpKpZ+Hu5iLyiIb8DzKZ/V5B4NruxEnDhWX3x8ukua0jH/C/ZTrahnSrzVVzufV81O3r+HUd334QkYti+3K4G8sE0HsNn7viRd1TP54MxP2dD8xh2zsnqpiVS50/UJ1lv5JsD535GiNoJorhRz631L7/udCrlDqA7Z9tiI1ghf57z9IWbfLuL+fOIIFnmuc9JpIOYKkp+cgQn1mtrc=
    IBM_ENTITLED_REGISTRY_USER: AgCHtSusy8ppQTVUblSprqvTieKZPJ/pzUFRJJk3hIn1stUnnld/GAZ5oZBXAIoKYJ/jDZ8ts0pezTWQZB+1GAnpSH1Ek9FOU2/ePa8RI2PO34Lu+99IQmjaA/YkmGVu0Kw7TF5GD16GkWJJrzHt+oqhqGBiIx7vWCB/ho+CpLM8xGWoa+JWrV2eyVbCdauTdgmvqWLFaeIiUfxOiEsInYsKzz+IjBtEhy6yB1opeWhXhE6BsRFQylb9ijTN3eREVaGEG7mTpAh+CAS2YcWtWqBgUU710OUEHGnUNg9UmHJsk7drcLezwLY/fzg4AVRnnlYOEUG/p4aQ6GbsrFD6RahCjp61WfjoP+uhFxzmsdKgYZPq4OsPQcbaFlBoQpbn3d9ryWN6K/rF697U4iv1cwDavKSE+pFsAJ9XmRL0ynEDgXtU+3OmzY6Si6P296y00fNyNFDXzKHv7Qw2KEY2gpumB1jGC9nREv4KeW89/Qy5fq47Kz/AGwpobfef/srRHiFdqWPXKPERUIsYmWf5v1XzoXnjDQBHzxvZBNSsMahRueTf9RQI0iH0dpo2QmBNr+9HTQpYl4iGXW/KRq4wG/P71pXre7sy2sh9HuK4g0OA+BGzOMes+KHMp5GBTeWrUa+nZzDhASpwx5bXT9htZBEiYhhSdgW1p6IwRrt8I5fM+e0nLg6ZVO2u8EkOzbnWoatTLA==
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

